// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/20/2026, 7:24:10 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/mariopazmino/Documents/GitHub/Food/monkey-food/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mariopazmino/Documents/GitHub/Food/monkey-food/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mariopazmino/Documents/GitHub/Food/monkey-food/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mariopazmino/Documents/GitHub/Food/monkey-food/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mariopazmino/Documents/GitHub/Food/monkey-food/plugins/**/*.{js,ts,mjs}","/Users/mariopazmino/Documents/GitHub/Food/monkey-food/composables/**/*.{js,ts,mjs}","/Users/mariopazmino/Documents/GitHub/Food/monkey-food/utils/**/*.{js,ts,mjs}","/Users/mariopazmino/Documents/GitHub/Food/monkey-food/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mariopazmino/Documents/GitHub/Food/monkey-food/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/mariopazmino/Documents/GitHub/Food/monkey-food/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/mariopazmino/Documents/GitHub/Food/monkey-food/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;